# Generated by Django 4.2.21 on 2025-05-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asana', '0002_delete_tas2k_task_assignee_task_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
